#!/bin/bash

cd /home/ziygawish/CURIS-workplace/cromwell-executions/reverse_flow/768ae5e9-568c-4936-af29-a6dc9e73afb9/call-reverse/shard-1/execution
tmpDir=$(mkdir -p "/home/ziygawish/CURIS-workplace/cromwell-executions/reverse_flow/768ae5e9-568c-4936-af29-a6dc9e73afb9/call-reverse/shard-1/tmp.ab0d3440" && echo "/home/ziygawish/CURIS-workplace/cromwell-executions/reverse_flow/768ae5e9-568c-4936-af29-a6dc9e73afb9/call-reverse/shard-1/tmp.ab0d3440")

export _JAVA_OPTIONS=-Djava.io.tmpdir="$tmpDir"
export TMPDIR="$tmpDir"
export HOME="$HOME"
(
cd /home/ziygawish/CURIS-workplace/cromwell-executions/reverse_flow/768ae5e9-568c-4936-af29-a6dc9e73afb9/call-reverse/shard-1/execution

)
out768ae5e9="${tmpDir}/out.$$" err768ae5e9="${tmpDir}/err.$$"
mkfifo "$out768ae5e9" "$err768ae5e9"
trap 'rm "$out768ae5e9" "$err768ae5e9"' EXIT
tee '/home/ziygawish/CURIS-workplace/cromwell-executions/reverse_flow/768ae5e9-568c-4936-af29-a6dc9e73afb9/call-reverse/shard-1/execution/stdout' < "$out768ae5e9" &
tee '/home/ziygawish/CURIS-workplace/cromwell-executions/reverse_flow/768ae5e9-568c-4936-af29-a6dc9e73afb9/call-reverse/shard-1/execution/stderr' < "$err768ae5e9" >&2 &
(
cd /home/ziygawish/CURIS-workplace/cromwell-executions/reverse_flow/768ae5e9-568c-4936-af29-a6dc9e73afb9/call-reverse/shard-1/execution


python3 /home/ziygawish/CURIS-workplace/reverse.py b.txt
)  > "$out768ae5e9" 2> "$err768ae5e9"
echo $? > /home/ziygawish/CURIS-workplace/cromwell-executions/reverse_flow/768ae5e9-568c-4936-af29-a6dc9e73afb9/call-reverse/shard-1/execution/rc.tmp
(
# add a .file in every empty directory to facilitate directory delocalization on the cloud
cd /home/ziygawish/CURIS-workplace/cromwell-executions/reverse_flow/768ae5e9-568c-4936-af29-a6dc9e73afb9/call-reverse/shard-1/execution
find . -type d -exec sh -c '[ -z "$(ls -A '"'"'{}'"'"')" ] && touch '"'"'{}'"'"'/.file' \;
)
(
cd /home/ziygawish/CURIS-workplace/cromwell-executions/reverse_flow/768ae5e9-568c-4936-af29-a6dc9e73afb9/call-reverse/shard-1/execution
sync


)
mv /home/ziygawish/CURIS-workplace/cromwell-executions/reverse_flow/768ae5e9-568c-4936-af29-a6dc9e73afb9/call-reverse/shard-1/execution/rc.tmp /home/ziygawish/CURIS-workplace/cromwell-executions/reverse_flow/768ae5e9-568c-4936-af29-a6dc9e73afb9/call-reverse/shard-1/execution/rc
