#!/bin/bash

cd /home/ziygawish/CURIS-workplace/cromwell-executions/reverse_flow/547f0152-73c1-4cc1-83a0-d90eda5d6103/call-reverse/shard-2/execution
tmpDir=$(mkdir -p "/home/ziygawish/CURIS-workplace/cromwell-executions/reverse_flow/547f0152-73c1-4cc1-83a0-d90eda5d6103/call-reverse/shard-2/tmp.f855fd6a" && echo "/home/ziygawish/CURIS-workplace/cromwell-executions/reverse_flow/547f0152-73c1-4cc1-83a0-d90eda5d6103/call-reverse/shard-2/tmp.f855fd6a")

export _JAVA_OPTIONS=-Djava.io.tmpdir="$tmpDir"
export TMPDIR="$tmpDir"
export HOME="$HOME"
(
cd /home/ziygawish/CURIS-workplace/cromwell-executions/reverse_flow/547f0152-73c1-4cc1-83a0-d90eda5d6103/call-reverse/shard-2/execution

)
out547f0152="${tmpDir}/out.$$" err547f0152="${tmpDir}/err.$$"
mkfifo "$out547f0152" "$err547f0152"
trap 'rm "$out547f0152" "$err547f0152"' EXIT
tee '/home/ziygawish/CURIS-workplace/cromwell-executions/reverse_flow/547f0152-73c1-4cc1-83a0-d90eda5d6103/call-reverse/shard-2/execution/stdout' < "$out547f0152" &
tee '/home/ziygawish/CURIS-workplace/cromwell-executions/reverse_flow/547f0152-73c1-4cc1-83a0-d90eda5d6103/call-reverse/shard-2/execution/stderr' < "$err547f0152" >&2 &
(
cd /home/ziygawish/CURIS-workplace/cromwell-executions/reverse_flow/547f0152-73c1-4cc1-83a0-d90eda5d6103/call-reverse/shard-2/execution


python reverse.py c.txt
)  > "$out547f0152" 2> "$err547f0152"
echo $? > /home/ziygawish/CURIS-workplace/cromwell-executions/reverse_flow/547f0152-73c1-4cc1-83a0-d90eda5d6103/call-reverse/shard-2/execution/rc.tmp
(
# add a .file in every empty directory to facilitate directory delocalization on the cloud
cd /home/ziygawish/CURIS-workplace/cromwell-executions/reverse_flow/547f0152-73c1-4cc1-83a0-d90eda5d6103/call-reverse/shard-2/execution
find . -type d -exec sh -c '[ -z "$(ls -A '"'"'{}'"'"')" ] && touch '"'"'{}'"'"'/.file' \;
)
(
cd /home/ziygawish/CURIS-workplace/cromwell-executions/reverse_flow/547f0152-73c1-4cc1-83a0-d90eda5d6103/call-reverse/shard-2/execution
sync


)
mv /home/ziygawish/CURIS-workplace/cromwell-executions/reverse_flow/547f0152-73c1-4cc1-83a0-d90eda5d6103/call-reverse/shard-2/execution/rc.tmp /home/ziygawish/CURIS-workplace/cromwell-executions/reverse_flow/547f0152-73c1-4cc1-83a0-d90eda5d6103/call-reverse/shard-2/execution/rc
